param(
  [string]$RegistryPath = (Join-Path $PSScriptRoot "..\configs\landing-product-registry.json"),
  [string]$ProfilesPath = (Join-Path $PSScriptRoot "..\configs\landing-product-gallery-profiles.json"),
  [string]$GalleryJsonOutputPath = (Join-Path $PSScriptRoot "..\library\landing-product-gallery.json"),
  [string]$GalleryMarkdownOutputPath = (Join-Path $PSScriptRoot "LANDING_PRODUCT_VISUAL_PLAYBOOK.md"),
  [string]$GalleryHtmlOutputPath = (Join-Path $PSScriptRoot "..\library\landing-product-gallery.html")
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Split-CamelCase {
  param([Parameter(Mandatory = $true)][string]$Text)

  $spaced = $Text -creplace '([A-Z]+)([A-Z][a-z])', '$1 $2'
  return ($spaced -creplace "([a-z0-9])([A-Z])", '$1 $2')
}

function Get-FamilyKey {
  param([Parameter(Mandatory = $true)][string]$ComponentName)

  $base = $ComponentName -replace '^LandingProduct', ''
  if ([string]::IsNullOrWhiteSpace($base)) {
    return "general"
  }

  $tokens = (Split-CamelCase -Text $base).Split(' ', [System.StringSplitOptions]::RemoveEmptyEntries)
  if ($tokens.Count -eq 0) {
    return "general"
  }

  return $tokens[0].ToLowerInvariant()
}

function Get-PreviewVariant {
  param([Parameter(Mandatory = $true)][string]$ComponentName)

  $sum = 0
  foreach ($char in $ComponentName.ToCharArray()) {
    $sum += [int][char]$char
  }

  return (($sum % 4) + 1)
}

function Encode-Html {
  param([Parameter(Mandatory = $true)][AllowEmptyString()][string]$Text)

  return [System.Net.WebUtility]::HtmlEncode($Text)
}

$registry = Get-Content -Raw -LiteralPath $RegistryPath | ConvertFrom-Json
$profiles = Get-Content -Raw -LiteralPath $ProfilesPath | ConvertFrom-Json

$defaultProfile = $profiles.default
$chaptersOut = [System.Collections.Generic.List[object]]::new()
$markdown = [System.Collections.Generic.List[string]]::new()

$markdown.Add('# Landing Product Visual Playbook')
$markdown.Add('')
$markdown.Add('Generated by `projects/ui-patterns/docs/generate-landing-product-visual-gallery.ps1`.')
$markdown.Add('')
$markdown.Add('Purpose: explore what already exists with less friction, clear visual defaults, and anti-repeat primary picks.')
$markdown.Add('')
$markdown.Add('Source shelf: `projects/ui-patterns/components/shelves/landing-product-system`')
$markdown.Add('')
$markdown.Add("Generated at: $([DateTimeOffset]::Now.ToString('u'))")
$markdown.Add('')

foreach ($chapter in $registry.chapters) {
  $profile = $profiles.chapters.$($chapter.key)
  if ($null -eq $profile) {
    $profile = $defaultProfile
  }

  $familyMap = @{}
  $componentsOut = [System.Collections.Generic.List[object]]::new()

  foreach ($componentName in $chapter.components) {
    $family = Get-FamilyKey -ComponentName $componentName
    if (-not $familyMap.ContainsKey($family)) {
      $familyMap[$family] = [System.Collections.Generic.List[string]]::new()
    }
    $familyMap[$family].Add($componentName)

    $componentsOut.Add([pscustomobject]@{
      name = $componentName
      file = "$componentName.tsx"
      path = "projects/ui-patterns/components/shelves/landing-product-system/$componentName.tsx"
      family = $family
    })
  }

  $primaryPicks = @(
    foreach ($familyKey in ($familyMap.Keys | Sort-Object)) {
      @($familyMap[$familyKey] | Sort-Object)[0]
    }
  )

  $chaptersOut.Add([pscustomobject]@{
    key = $chapter.key
    label = $chapter.label
    description = $chapter.description
    tone = $profile.tone
    visualDefaults = [pscustomobject]@{
      classes = $profile.classes
      cssVars = $profile.cssVars
    }
    stats = [pscustomobject]@{
      components = $chapter.count
      families = ($familyMap.Keys | Measure-Object).Count
      primaryPicks = $primaryPicks.Count
    }
    primaryPicks = $primaryPicks
    components = $componentsOut
  })

  $markdown.Add("## $($chapter.label)")
  $markdown.Add("")
  $markdown.Add($chapter.description)
  $markdown.Add('')
  $markdown.Add("- Tone: $($profile.tone)")
  $markdown.Add("- Default surface: ``$($profile.classes.surface)``")
  $markdown.Add("- Default accent: ``$($profile.classes.accent)``")
  $markdown.Add("- Default chip: ``$($profile.classes.chip)``")
  $markdown.Add("- Components: $($chapter.count)")
  $markdown.Add("- Family groups: $(($familyMap.Keys | Measure-Object).Count)")
  $markdown.Add('')
  $markdown.Add('Curated picks (chapter highlights):')

  foreach ($highlight in $chapter.highlights) {
    $markdown.Add(("- [{0}](../components/shelves/landing-product-system/{0}.tsx)" -f $highlight))
  }

  $markdown.Add('')
  $markdown.Add('Primary picks (anti-repeat, one per family):')

  foreach ($pick in $primaryPicks) {
    $markdown.Add(("- [{0}](../components/shelves/landing-product-system/{0}.tsx)" -f $pick))
  }

  $markdown.Add('')
  $markdown.Add('Full wall:')

  foreach ($componentName in ($chapter.components | Sort-Object)) {
    $markdown.Add("- [$componentName](../components/shelves/landing-product-system/$componentName.tsx)")
  }

  $markdown.Add('')
}

$galleryObject = [pscustomobject]@{
  generatedAt = [DateTimeOffset]::Now.ToString('o')
  source = [pscustomobject]@{
    registry = $RegistryPath
    profiles = $ProfilesPath
    shelf = 'projects/ui-patterns/components/shelves/landing-product-system'
  }
  stats = [pscustomobject]@{
    chapters = $registry.chapters.Count
    totalComponents = $registry.stats.landingProductComponents
  }
  chapters = $chaptersOut
}

$html = [System.Collections.Generic.List[string]]::new()
$html.Add('<!doctype html>')
$html.Add('<html lang="en">')
$html.Add('<head>')
$html.Add('  <meta charset="utf-8" />')
$html.Add('  <meta name="viewport" content="width=device-width, initial-scale=1" />')
$html.Add('  <title>Landing Product Gallery</title>')
$html.Add('  <style>')
$html.Add('    :root { color-scheme: dark; --bg: #081018; --panel: #0f1722; --panel-2: #131d29; --line: #223043; --ink: #edf3fb; --muted: #94a7bd; --shadow: 0 20px 60px rgba(0,0,0,.35); }')
$html.Add('    * { box-sizing: border-box; }')
$html.Add('    body { margin: 0; font-family: Aptos, "Trebuchet MS", "Segoe UI", sans-serif; background: radial-gradient(circle at top, #122033 0%, #081018 45%, #050b12 100%); color: var(--ink); }')
$html.Add('    a { color: inherit; }')
$html.Add('    .shell { display: grid; grid-template-columns: 280px 1fr; min-height: 100vh; }')
$html.Add('    .sidebar { position: sticky; top: 0; align-self: start; height: 100vh; padding: 28px 20px; border-right: 1px solid var(--line); background: rgba(8,16,24,.82); backdrop-filter: blur(14px); }')
$html.Add('    .brand { margin-bottom: 24px; }')
$html.Add('    .eyebrow { margin: 0 0 8px; font-size: 11px; letter-spacing: .24em; text-transform: uppercase; color: var(--muted); }')
$html.Add('    .title { margin: 0; font-size: 30px; line-height: 1.05; }')
$html.Add('    .lede { margin: 12px 0 0; color: var(--muted); font-size: 14px; line-height: 1.6; }')
$html.Add('    .stats { display: grid; gap: 10px; margin: 22px 0; }')
$html.Add('    .stat { padding: 12px 14px; border: 1px solid var(--line); border-radius: 14px; background: rgba(255,255,255,.02); }')
$html.Add('    .stat strong { display: block; font-size: 22px; }')
$html.Add('    .stat span { color: var(--muted); font-size: 12px; }')
$html.Add('    .nav { display: grid; gap: 8px; }')
$html.Add('    .nav a { display: block; padding: 10px 12px; border: 1px solid transparent; border-radius: 12px; color: var(--muted); text-decoration: none; font-size: 14px; }')
$html.Add('    .nav a:hover { border-color: var(--line); background: rgba(255,255,255,.03); color: var(--ink); }')
$html.Add('    .main { padding: 28px; }')
$html.Add('    .hero { display: grid; gap: 18px; grid-template-columns: 1.1fr .9fr; padding: 26px; border: 1px solid var(--line); border-radius: 24px; background: linear-gradient(135deg, rgba(255,255,255,.04), rgba(255,255,255,.01)); box-shadow: var(--shadow); }')
$html.Add('    .hero h2 { margin: 0; font-size: 42px; line-height: 1.02; }')
$html.Add('    .hero p { margin: 0; color: var(--muted); line-height: 1.7; }')
$html.Add('    .hero-grid { display: grid; grid-template-columns: repeat(2, minmax(0,1fr)); gap: 12px; }')
$html.Add('    .mini { padding: 14px; border: 1px solid var(--line); border-radius: 16px; background: rgba(255,255,255,.025); }')
$html.Add('    .mini strong { display: block; font-size: 20px; margin-bottom: 6px; }')
$html.Add('    .mini span { color: var(--muted); font-size: 12px; }')
$html.Add('    .mini a { color: var(--ink); }')
$html.Add('    .chapter { margin-top: 28px; padding: 22px; border: 1px solid var(--line); border-radius: 24px; background: linear-gradient(180deg, rgba(255,255,255,.025), rgba(255,255,255,.01)); box-shadow: var(--shadow); }')
$html.Add('    .chapter-head { display: flex; justify-content: space-between; gap: 20px; align-items: start; margin-bottom: 18px; }')
$html.Add('    .chapter-head h3 { margin: 0; font-size: 28px; }')
$html.Add('    .chapter-head p { margin: 10px 0 0; color: var(--muted); line-height: 1.6; max-width: 72ch; }')
$html.Add('    .tone { display: inline-flex; align-items: center; gap: 8px; padding: 8px 12px; border-radius: 999px; border: 1px solid var(--line); font-size: 12px; text-transform: uppercase; letter-spacing: .18em; white-space: nowrap; }')
$html.Add('    .chips, .links { display: flex; flex-wrap: wrap; gap: 10px; }')
$html.Add('    .chip { display: inline-flex; align-items: center; padding: 8px 12px; border-radius: 999px; border: 1px solid var(--line); text-decoration: none; font-size: 13px; box-shadow: inset 0 1px 0 rgba(255,255,255,.08); }')
$html.Add('    .section-label { margin: 18px 0 10px; font-size: 12px; letter-spacing: .18em; text-transform: uppercase; color: var(--muted); }')
$html.Add('    .grid { display: grid; grid-template-columns: repeat(3, minmax(0,1fr)); gap: 12px; }')
$html.Add('    .card { overflow: hidden; border-radius: 20px; border: 1px solid rgba(255,255,255,.08); background: linear-gradient(180deg, rgba(255,255,255,.04), rgba(255,255,255,.015)); box-shadow: 0 18px 40px rgba(0,0,0,.24); }')
$html.Add('    .preview { position: relative; min-height: 172px; padding: 16px; background: radial-gradient(circle at top left, color-mix(in srgb, hsl(var(--accent-hsl)) 26%, transparent), transparent 42%), linear-gradient(180deg, rgba(255,255,255,.06), rgba(255,255,255,.015)); border-bottom: 1px solid rgba(255,255,255,.06); }')
$html.Add('    .preview::before { content: ""; position: absolute; inset: 0; background: linear-gradient(135deg, color-mix(in srgb, hsl(var(--accent-hsl)) 12%, transparent), transparent 55%); opacity: .9; }')
$html.Add('    .preview::after { content: ""; position: absolute; inset: 10px; border: 1px solid rgba(255,255,255,.08); border-radius: 16px; pointer-events: none; }')
$html.Add('    .preview-top { display: flex; justify-content: space-between; align-items: center; margin-bottom: 14px; position: relative; z-index: 1; }')
$html.Add('    .preview-family { display: inline-flex; align-items: center; gap: 8px; font-size: 11px; letter-spacing: .16em; text-transform: uppercase; color: color-mix(in srgb, hsl(var(--accent-hsl)) 60%, white); }')
$html.Add('    .preview-family::before { content: ""; width: 8px; height: 8px; border-radius: 999px; background: hsl(var(--accent-hsl)); box-shadow: 0 0 18px color-mix(in srgb, hsl(var(--accent-hsl)) 80%, transparent); }')
$html.Add('    .preview-name { font-size: 12px; color: rgba(237,243,251,.68); max-width: 56%; text-align: right; }')
$html.Add('    .preview-frame { position: relative; z-index: 1; display: grid; gap: 12px; }')
$html.Add('    .preview-hero { height: 54px; border-radius: 14px; background: linear-gradient(135deg, color-mix(in srgb, hsl(var(--accent-hsl)) 55%, rgba(255,255,255,.18)), rgba(255,255,255,.06)); box-shadow: inset 0 1px 0 rgba(255,255,255,.16); }')
$html.Add('    .preview-lines { display: grid; gap: 8px; }')
$html.Add('    .preview-lines span { display: block; height: 8px; border-radius: 999px; background: rgba(255,255,255,.18); }')
$html.Add('    .preview-lines span:nth-child(2) { width: 76%; }')
$html.Add('    .preview-lines span:nth-child(3) { width: 58%; }')
$html.Add('    .preview-panels { display: grid; grid-template-columns: repeat(3, minmax(0,1fr)); gap: 10px; }')
$html.Add('    .preview-panels span { display: block; height: 42px; border-radius: 12px; background: rgba(255,255,255,.08); border: 1px solid rgba(255,255,255,.1); }')
$html.Add('    .preview-v2 .preview-hero { height: 42px; width: 72%; }')
$html.Add('    .preview-v2 .preview-panels { grid-template-columns: 1.2fr .8fr; }')
$html.Add('    .preview-v2 .preview-panels span:last-child { height: 96px; }')
$html.Add('    .preview-v3 .preview-frame { grid-template-columns: 1.1fr .9fr; align-items: end; }')
$html.Add('    .preview-v3 .preview-lines { align-self: stretch; }')
$html.Add('    .preview-v3 .preview-panels { grid-template-columns: 1fr; }')
$html.Add('    .preview-v3 .preview-panels span { height: 28px; }')
$html.Add('    .preview-v4 .preview-hero { height: 70px; }')
$html.Add('    .preview-v4 .preview-panels { grid-template-columns: repeat(4, minmax(0,1fr)); }')
$html.Add('    .preview-v4 .preview-panels span:nth-child(1) { grid-column: span 2; }')
$html.Add('    .card-body { padding: 16px; display: grid; gap: 10px; }')
$html.Add('    .card-kicker { font-size: 11px; letter-spacing: .18em; text-transform: uppercase; color: color-mix(in srgb, hsl(var(--accent-hsl)) 50%, #dce7f5); }')
$html.Add('    .card-title { margin: 0; font-size: 28px; line-height: .98; letter-spacing: -.03em; max-width: 12ch; }')
$html.Add('    .card-body p { margin: 0; }')
$html.Add('    .meta { color: var(--muted); font-size: 13px; line-height: 1.45; max-width: 34ch; }')
$html.Add('    .card-actions { display: flex; justify-content: flex-start; align-items: center; gap: 10px; margin-top: 6px; }')
$html.Add('    .source-link { display: inline-flex; align-items: center; gap: 8px; padding: 8px 10px; border-radius: 999px; border: 1px solid rgba(255,255,255,.08); text-decoration: none; font-size: 12px; color: var(--ink); }')
$html.Add('    .source-link:hover { border-color: color-mix(in srgb, hsl(var(--accent-hsl)) 35%, #223043); background: color-mix(in srgb, hsl(var(--accent-hsl)) 10%, transparent); }')
$html.Add('    @media (max-width: 1080px) { .shell { grid-template-columns: 1fr; } .sidebar { position: relative; height: auto; border-right: 0; border-bottom: 1px solid var(--line); } .hero { grid-template-columns: 1fr; } .grid { grid-template-columns: repeat(2, minmax(0,1fr)); } }')
$html.Add('    @media (max-width: 720px) { .main { padding: 18px; } .sidebar { padding: 18px; } .hero h2 { font-size: 32px; } .grid { grid-template-columns: 1fr; } .hero-grid { grid-template-columns: 1fr; } .chapter-head { flex-direction: column; } }')
$html.Add('  </style>')
$html.Add('</head>')
$html.Add('<body>')
$html.Add('  <div class="shell">')
$html.Add('    <aside class="sidebar">')
$html.Add('      <div class="brand">')
$html.Add('        <p class="eyebrow">UI Lab Gallery</p>')
$html.Add('        <h1 class="title">Landing Product Shelf</h1>')
$html.Add('        <p class="lede">A visual-first browsing surface for the existing archive. No new variants. No duplicate work. Just curated entrypoints, color defaults, and anti-repeat picks.</p>')
$html.Add('      </div>')
$html.Add('      <div class="stats">')
$html.Add(('        <div class="stat"><strong>{0}</strong><span>LandingProduct components</span></div>' -f $registry.stats.landingProductComponents))
$html.Add(('        <div class="stat"><strong>{0}</strong><span>Gallery chapters</span></div>' -f $registry.chapters.Count))
$html.Add(('        <div class="stat"><strong>{0}</strong><span>Starter kits in registry</span></div>' -f $registry.starterKits.Count))
$html.Add('      </div>')
$html.Add('      <nav class="nav">')

foreach ($chapter in $chaptersOut) {
  $html.Add(('        <a href="#{0}">{1}</a>' -f (Encode-Html $chapter.key), (Encode-Html $chapter.label)))
}

$html.Add('      </nav>')
$html.Add('    </aside>')
$html.Add('    <main class="main">')
$html.Add('      <section class="hero">')
$html.Add('        <div>')
$html.Add('          <p class="eyebrow">Showroom Mode</p>')
$html.Add('          <h2>Explore the shelf like a gallery, not a graveyard of filenames.</h2>')
$html.Add('          <p>This showroom groups the archive by chapter, assigns a default visual tone, surfaces the official highlights, then narrows the wall to anti-repeat picks so you can browse what already exists without multiplying variants. For actual React output, jump to the live gallery.</p>')
$html.Add('        </div>')
$html.Add('        <div class="hero-grid">')
$html.Add('          <div class="mini"><strong>Curated picks</strong><span>Chapter highlights from the registry, good first-view surfaces.</span></div>')
$html.Add('          <div class="mini"><strong>Primary picks</strong><span>One representative per detected family to reduce repetition.</span></div>')
$html.Add('          <div class="mini"><strong>Live renders</strong><span><a href="./landing-product-live-gallery.html">Open the real React gallery</a> for curated sections rendered from source.</span></div>')
$html.Add('          <div class="mini"><strong>Full wall</strong><span>Every component stays accessible when you need exhaustive browse depth.</span></div>')
$html.Add('        </div>')
$html.Add('      </section>')

foreach ($chapter in $chaptersOut) {
  $accent = $chapter.visualDefaults.cssVars.'--gallery-accent'
  $html.Add(('      <section id="{0}" class="chapter" style="--accent-hsl:{1};">' -f (Encode-Html $chapter.key), (Encode-Html $accent)))
  $html.Add('        <div class="chapter-head">')
  $html.Add('          <div>')
  $html.Add(("            <h3>{0}</h3>" -f (Encode-Html $chapter.label)))
  $html.Add(("            <p>{0}</p>" -f (Encode-Html $chapter.description)))
  $html.Add('          </div>')
  $html.Add(('          <div class="tone" style="color:hsl(var(--accent-hsl)); border-color: color-mix(in srgb, hsl(var(--accent-hsl)) 35%, #223043); background: color-mix(in srgb, hsl(var(--accent-hsl)) 10%, transparent);">{0}</div>' -f (Encode-Html $chapter.tone)))
  $html.Add('        </div>')
  $html.Add(('        <div class="section-label">Curated picks - {0} components - {1} family groups</div>' -f $chapter.stats.components, $chapter.stats.families))
  $html.Add('        <div class="chips">')
  foreach ($pick in $registry.chapters | Where-Object { $_.key -eq $chapter.key } | Select-Object -ExpandProperty highlights) {
    $html.Add(('          <span class="chip" style="color:hsl(var(--accent-hsl)); border-color: color-mix(in srgb, hsl(var(--accent-hsl)) 30%, #223043); background: color-mix(in srgb, hsl(var(--accent-hsl)) 9%, transparent);">{0}</span>' -f (Encode-Html $pick)))
  }
  $html.Add('        </div>')
  $html.Add('        <div class="section-label">Primary picks - anti-repeat representatives</div>')
  $html.Add('        <div class="grid">')
  foreach ($pick in $chapter.primaryPicks) {
    $comp = $chapter.components | Where-Object { $_.name -eq $pick } | Select-Object -First 1
    $variant = Get-PreviewVariant -ComponentName $pick
    $title = Split-CamelCase -Text ($pick -replace '^LandingProduct', '')
    $familyLabel = ($title -split ' ')[0]
    $html.Add('          <article class="card">')
    $html.Add(('            <div class="preview preview-v{0}">' -f $variant))
    $html.Add('              <div class="preview-top">')
    $html.Add(('                <div class="preview-family">{0}</div>' -f (Encode-Html $familyLabel)))
    $html.Add(('                <div class="preview-name">{0}</div>' -f (Encode-Html $title)))
    $html.Add('              </div>')
    $html.Add('              <div class="preview-frame">')
    $html.Add('                <div>')
    $html.Add('                  <div class="preview-hero"></div>')
    $html.Add('                  <div class="preview-lines"><span></span><span></span><span></span></div>')
    $html.Add('                </div>')
    $html.Add('                <div class="preview-panels"><span></span><span></span><span></span><span></span></div>')
    $html.Add('              </div>')
    $html.Add('            </div>')
    $html.Add('            <div class="card-body">')
    $html.Add(('              <div class="card-kicker">{0}</div>' -f (Encode-Html $chapter.label)))
    $html.Add(('              <h4 class="card-title">{0}</h4>' -f (Encode-Html $title)))
    $html.Add(('              <p class="meta">Family {0}. Visual browse poster for the existing section.</p>' -f (Encode-Html $familyLabel.ToLowerInvariant())))
    $html.Add('              <div class="card-actions">')
    $html.Add(('                <a class="source-link" href="../components/shelves/landing-product-system/{0}.tsx" target="_blank" rel="noreferrer">Source</a>' -f (Encode-Html $pick)))
    $html.Add('              </div>')
    $html.Add('            </div>')
    $html.Add('          </article>')
  }
  $html.Add('        </div>')
  $html.Add('      </section>')
}

$html.Add('    </main>')
$html.Add('  </div>')
$html.Add('</body>')
$html.Add('</html>')

$galleryObject | ConvertTo-Json -Depth 12 | Set-Content -LiteralPath $GalleryJsonOutputPath -Encoding utf8
$markdown -join "`r`n" | Set-Content -LiteralPath $GalleryMarkdownOutputPath -Encoding utf8
$html -join "`r`n" | Set-Content -LiteralPath $GalleryHtmlOutputPath -Encoding utf8

Write-Output "Generated gallery json: $GalleryJsonOutputPath"
Write-Output "Generated gallery markdown: $GalleryMarkdownOutputPath"
Write-Output "Generated gallery html: $GalleryHtmlOutputPath"
